#CI项目名
name: OpenWrt-NSS

on:
  #自动编译：每天早上4点
  #schedule:
    #- cron: 0 20 * * *
  #手动编译
  workflow_dispatch:

#CI权限
permissions: write-all

#CI任务
jobs:
  owrt_config:
    #调用公用编译核心OWRT-CORE.yml
    uses: ./.github/workflows/OWRT-CORE.yml
    with:
      #编译
      OWRT_TARGET: AX9000-NSS
      #默认主题
      OWRT_THEME: design
      #默认主机名
      #OWRT_NAME: iPQ807X
      OWRT_NAME: AX9000
      #默认密码，仅作展示，更改无效
      OWRT_PW: password
      #默认地址
      OWRT_IP: 10.0.10.1
      #默认源码
      OWRT_URL: -b 24.10-nss https://github.com/qosmio/openwrt-ipq.git
